- hosts: web
  tasks:
   - package: "name=httpd state=present"
   - copy: "dest=/var/www/html/index.html content='Welcome to my site!!!'"
   - service: "name=httpd state=started"
   - firewalld: "port=80/tcp state=enabled immediate=yes"

